# Shared makefile code providing support for Kbuild make. It is included
# by every `Makefile.am` that needs Kbuild support with:
# ```
# include $(top_srcdir)/Makefile.kbuild
# ```
KBUILD = $(MAKE) -C "$(LINUX_SOURCE_DIR)" M="$(abs_builddir)" INSTALL_MOD_DIR="$(INSTALL_MOD_DIR)"


modules:
	@if test -n "$(LINUX_SOURCE_DIR)"; then \
	  $(KBUILD) modules; \
	fi

modules_install:
	@if test -n "$(LINUX_SOURCE_DIR)"; then \
	  $(KBUILD) modules_install; \
	fi


# Override default `clean` target to call Kbuild clean *before* automake
# `clean` (see #5 for the rationale).
clean: kbuild-clean
	@if test -z "$(SUBDIRS)"; then \
	  $(MAKE) $(AM_MAKEFLAGS) clean-am ; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) clean-recursive ; \
	fi

kbuild-clean:
	@if test -n "$(LINUX_SOURCE_DIR)"; then \
	  $(KBUILD) clean; \
	fi

.PHONY: kbuild-clean
