/*****************************************************************************
 *
 *  Integration test: the sim transport selected the production way — via
 *  the registry (ec_transport_create(EC_TRANSPORT_SIM, <file>)) with the
 *  bus built from a description file by sim_open(), exactly as lcec does
 *  for transportType=sim. Complements test_sim_scan, which injects a
 *  pre-built sim_bus directly (the test-only path).
 *
 *  Writes a two-slave description file, creates the transport by type,
 *  runs a real userspace master on it, and verifies the scan reports the
 *  identities parsed from the file. Also checks that the library
 *  open/close lifecycle frees the file-owned bus (no leak, no double free
 *  — run under valgrind/ASan for the memory assertions).
 *
 *  This file is part of the IgH EtherCAT Master.
 *
 *  The IgH EtherCAT Master is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License version 2, as
 *  published by the Free Software Foundation.
 *
 ****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include "ecrt.h"
#include "ectp.h"

#include "test.h"

/* Written to the description file; asserted back after the scan. */
static const struct {
    uint32_t vendor_id;
    uint32_t product_code;
    uint32_t revision_number;
    uint32_t serial_number;
    uint16_t alias;
} expect[2] = {
    { 0x00000E17, 0x5134000A, 0x00010000, 8001, 7 },
    { 0x00000002, 0x044C2C52, 0x00110000, 1002, 0 },
};

static int write_sim_file(const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f) {
        return -1;
    }
    /* Slave 0: a CoE slave with a mailbox and 4/4 bytes of process data
     * plus a preset OD entry. Slave 1: a plain slave, no mailbox. */
    fprintf(f,
        "# generated by test_sim_transport_file\n"
        "slave 0\n"
        "  vendor   0x00000E17\n"
        "  product  0x5134000A\n"
        "  revision 0x00010000\n"
        "  serial   8001\n"
        "  alias    7\n"
        "  mbox_out 0x1000 128\n"
        "  mbox_in  0x1080 128\n"
        "  sm2      0x1100 4\n"
        "  sm3      0x1400 4\n"
        "  od       0x2000 0 4 0xDEADBEEF\n"
        "slave 1\n"
        "  vendor   0x00000002\n"
        "  product  0x044C2C52\n"
        "  revision 0x00110000\n"
        "  serial   1002\n");
    fclose(f);
    return 0;
}

int main(void)
{
    char path[128];
    ec_transport_t *transport;
    ec_master_t *master;
    ec_master_info_t info;
    unsigned int i;

    snprintf(path, sizeof(path), "%s/ecsim-%d.sim",
            getenv("TMPDIR") ? getenv("TMPDIR") : "/tmp", (int) getpid());

    TEST_CHECK_EQ(0, write_sim_file(path));

    /* Select the transport by type, as conf.c does for transportType=sim;
     * the interface string is the description-file path. */
    transport = ec_transport_create(EC_TRANSPORT_SIM, path);
    TEST_CHECK(transport != NULL);
    if (!transport) {
        unlink(path);
        return test_done("test_sim_transport_file");
    }

    TEST_CHECK_EQ(0, ecrt_lib_init(NULL, NULL /* no IPC server */));

    /* ecrt_startup_master() calls ec_transport_open() -> sim_open(), which
     * parses the file and builds the emulated bus; startup then blocks
     * until the scan completes. */
    master = ecrt_startup_master(0, transport, NULL, 0, -1);
    TEST_CHECK(master != NULL);

    if (master) {
        TEST_CHECK_EQ(0, ecrt_master(master, &info));
        TEST_CHECK_EQ(2, info.slave_count);

        for (i = 0; i < 2; i++) {
            ec_slave_info_t slave;
            TEST_CHECK_EQ(0, ecrt_master_get_slave(master, i, &slave));
            TEST_CHECK_EQ(expect[i].vendor_id, slave.vendor_id);
            TEST_CHECK_EQ(expect[i].product_code, slave.product_code);
            TEST_CHECK_EQ(expect[i].revision_number, slave.revision_number);
            TEST_CHECK_EQ(expect[i].serial_number, slave.serial_number);
            TEST_CHECK_EQ(expect[i].alias, slave.alias);
        }

        /* Library closes the transport (sim_close frees the file-owned
         * bus); the caller still owns the transport object itself. */
        ecrt_release_master(master);
    }

    ecrt_lib_cleanup();
    ec_transport_destroy(transport);
    unlink(path);

    return test_done("test_sim_transport_file");
}
